version: "3"
services:
  python_import_sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: python_import_sample-image
    container_name: python_import_sample-container
    tty: true
